document.getElementById("AppCaption").innerHTML = "My App Caption"
document.getElementById("Header").innerHTML = "My Header"
document.getElementById("Sign").innerHTML = "My Sign"
document.getElementById("StacksActive").innerHTML = "My StacksActive"
document.getElementById("StackForeground").innerHTML = "My StackForeground"
document.getElementById("Footer").innerHTML = "My Footer"
document.getElementById("Clipboard").innerHTML = "My Clipboard"
document.getElementById("Debug").innerHTML = "My Debug"
